#!/usr/bin/env bash
# install.sh — install the Hermes `maxun` web-extraction tool + skill.
#
# Idempotent. Copies:
#   tools/maxun_tool.py        -> <hermes-agent>/tools/
#   tools/maxun_tool_audit.py  -> <hermes-agent>/tools/
#   skills/maxun-tool/SKILL.md -> ~/.hermes/skills/maxun-tool/
#
# It does NOT modify core files (toolsets.py / config.py) automatically — those
# edits are documented in README.md and applied by the user (or a Hermes agent)
# because they touch the agent core. The tool self-registers via the registry
# import, but it only becomes *exposed* to the model after being added to a
# toolset (see README "Wire into a toolset").
#
# Usage:
#   ./install.sh [--hermes-agent /path/to/hermes-agent]
#
# Privacy: this repo contains NO secrets, API keys, or personal paths. The
# Maxun API key is generated by the user in their own Maxun instance.

set -euo pipefail

HERMES_AGENT="${1:-}"
if [[ -z "$HERMES_AGENT" ]]; then
  # Try a few common locations.
  for p in \
    "$HOME/.hermes/hermes-agent" \
    "$(pwd)/hermes-agent" \
    "/opt/hermes-agent"; do
    if [[ -f "$p/tools/registry.py" ]]; then HERMES_AGENT="$p"; break; fi
  done
fi

if [[ -z "$HERMES_AGENT" || ! -f "$HERMES_AGENT/tools/registry.py" ]]; then
  echo "ERROR: could not locate hermes-agent (need tools/registry.py)." >&2
  echo "Pass it explicitly:  ./install.sh /path/to/hermes-agent" >&2
  exit 1
fi

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$HOME/.hermes/skills/maxun-tool"

echo "==> Hermes agent: $HERMES_AGENT"

# 1) Tool files
cp "$SRC/tools/maxun_tool.py"        "$HERMES_AGENT/tools/"
cp "$SRC/tools/maxun_tool_audit.py"  "$HERMES_AGENT/tools/"
echo "    copied tool -> $HERMES_AGENT/tools/"

# 2) Skill
mkdir -p "$SKILL_DIR/references"
cp "$SRC/skills/maxun-tool/SKILL.md" "$SKILL_DIR/"
cp "$SRC/skills/maxun-tool/references/"*.md "$SKILL_DIR/references/" 2>/dev/null || true
echo "    copied skill -> $SKILL_DIR/"

# 3) Verify the tool imports cleanly
( cd "$HERMES_AGENT" && python3 -c "import tools.maxun_tool as m; assert m.MAXUN_SCHEMA['name']=='maxun'; print('    import OK, schema name =', m.MAXUN_SCHEMA['name'])" ) \
  || { echo "ERROR: tool failed to import in $HERMES_AGENT" >&2; exit 1; }

echo
echo "==> Installed. Next steps (see README.md):"
echo "   1. Add 'maxun' to a toolset in $HERMES_AGENT/toolsets.py"
echo "      (e.g. _HERMES_CORE_TOOLS list, or the 'web' toolset tools[])."
echo "   2. Add MAXUN_API_KEY / MAXUN_API_URL to OPTIONAL_ENV_VARS in"
echo "      $HERMES_AGENT/hermes_cli/config.py (optional — lets 'hermes setup'"
echo "      discover them)."
echo "   3. Self-host Maxun (see skills/maxun-tool/references/maxun-selfhost-recipe.md)"
echo "      and generate an API key, OR use Maxun cloud."
echo "   4. Set the env vars (hermes setup / /secret) and restart Hermes."
echo "   5. Run the audit:  python3 $HERMES_AGENT/tools/maxun_tool_audit.py"
